---
- name: Install vsftpd
  apt:
    name: vsftpd
    update_cache: yes
    state: present
    
- name: Delete old config
  file:
    path: /etc/vsftpd.conf
    state: absent
    
- name: Create config
  blockinfile:
    path: /etc/vsftpd.conf
    create: yes
    marker: ""
    block: |
      listen=YES
      listen_ipv6=NO
      anonymous_enable=YES
      local_enable=YES
      dirmessage_enable=YES
      use_localtime=YES
      xferlog_enable=YES
      connect_from_port_20=YES
      ftpd_banner=Welcome to homework FTP service.
      secure_chroot_dir=/var/run/vsftpd/empty
      pam_service_name=vsftpd
    
- name: Restart vsftpd
  service:
    name: vsftpd
    state: restarted
